<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NIM | Художник</title>
    <style>
        :root {
            --bg-color: #f5f5f7;
            --text-color: #1d1d1f;
            --accent-color: #0066cc;
            --section-padding: 80px;
        }
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            line-height: 1.5;
            overflow-x: hidden;
        }
        
        .navbar {
            position: fixed;
            top: 0;
            width: 100%;
            height: 44px;
            background-color: rgba(245, 245, 247, 0.8);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 1000;
        }
        
        .nav-links {
            display: flex;
            gap: 24px;
        }
        
        .nav-links a {
            color: var(--text-color);
            text-decoration: none;
            font-size: 12px;
            font-weight: 400;
            opacity: 0.8;
            transition: opacity 0.3s;
        }
        
        .nav-links a:hover {
            opacity: 1;
        }
        
        .hero {
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            padding-top: 44px;
            background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');
            background-size: cover;
            background-position: center;
            color: white;
        }
        
        .hero h1 {
            font-size: 72px;
            font-weight: 600;
            margin-bottom: 20px;
            text-shadow: 0 2px 10px rgba(0,0,0,0.5);
        }
        
        .hero p {
            font-size: 24px;
            max-width: 700px;
            margin-bottom: 40px;
            text-shadow: 0 2px 5px rgba(0,0,0,0.5);
        }
        
        .scroll-indicator {
            position: absolute;
            bottom: 40px;
            animation: bounce 2s infinite;
            color: white;
        }
        
        @keyframes bounce {
            0%, 20%, 50%, 80%, 100% {transform: translateY(0);}
            40% {transform: translateY(-20px);}
            60% {transform: translateY(-10px);}
        }
        
        section {
            padding: var(--section-padding) 0;
            position: relative;
        }
        
        .section-header {
            text-align: center;
            margin-bottom: 60px;
        }
        
        .section-header h2 {
            font-size: 40px;
            font-weight: 600;
            margin-bottom: 10px;
        }
        
        .section-header p {
            font-size: 21px;
            color: #86868b;
            max-width: 600px;
            margin: 0 auto;
        }
        
        .gallery {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 20px;
            padding: 0 20px;
        }
        
        .artwork {
            position: relative;
            overflow: hidden;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s;
        }
        
        .artwork:hover {
            transform: scale(1.02);
        }
        
        .artwork img {
            width: 100%;
            height: 400px;
            object-fit: cover;
            display: block;
        }
        
        .artwork-info {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background: linear-gradient(to top, rgba(0, 0, 0, 0.7), transparent);
            color: white;
            padding: 20px;
        }
        
        .sold-badge {
            position: absolute;
            top: 15px;
            right: 15px;
            background-color: #ff3b30;
            color: white;
            padding: 5px 10px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: bold;
        }
        
        .price-tag {
            position: absolute;
            top: 15px;
            left: 15px;
            background-color: rgba(0,0,0,0.7);
            color: white;
            padding: 5px 10px;
            border-radius: 20px;
            font-size: 14px;
            font-weight: bold;
        }
        
        .timeline {
            max-width: 800px;
            margin: 0 auto;
            padding: 0 20px;
        }
        
        .timeline-item {
            display: flex;
            margin-bottom: 40px;
        }
        
        .timeline-year {
            flex: 0 0 120px;
            font-weight: 600;
            color: var(--accent-color);
        }
        
        .timeline-content {
            flex: 1;
            border-left: 2px solid var(--accent-color);
            padding-left: 30px;
            padding-bottom: 20px;
        }
        
        .timeline-content h3 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        
        .collections {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 30px;
            padding: 0 20px;
        }
        
        .collection {
            flex: 1;
            min-width: 300px;
            max-width: 400px;
            background: white;
            border-radius: 18px;
            overflow: hidden;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.05);
        }
        
        .collection img {
            width: 100%;
            height: 200px;
            object-fit: cover;
        }
        
        .collection-info {
            padding: 25px;
        }
        
        .collection-info h3 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        
        .contact {
            max-width: 600px;
            margin: 0 auto;
            text-align: center;
            padding: 0 20px;
        }
        
        .contact p {
            margin-bottom: 30px;
            font-size: 21px;
        }
        
        .contact-btn {
            display: inline-block;
            background-color: var(--accent-color);
            color: white;
            padding: 12px 30px;
            border-radius: 30px;
            text-decoration: none;
            font-weight: 500;
            transition: background-color 0.3s;
        }
        
        .contact-btn:hover {
            background-color: #004080;
        }
        
        footer {
            background-color: var(--text-color);
            color: white;
            padding: 40px 20px;
            text-align: center;
            font-size: 12px;
        }
        
        @media (max-width: 768px) {
            .hero h1 {
                font-size: 48px;
            }
            
            .hero p {
                font-size: 20px;
                padding: 0 20px;
            }
            
            .section-header h2 {
                font-size: 32px;
            }
            
            .timeline-item {
                flex-direction: column;
            }
            
            .timeline-year {
                margin-bottom: 10px;
            }
            
            .timeline-content {
                border-left: none;
                border-top: 2px solid var(--accent-color);
                padding-left: 0;
                padding-top: 20px;
            }
        }
    </style>
</head>
<body>
    <nav class="navbar">
        <div class="nav-links">
            <a href="#works">Работы</a>
            <a href="#history">История</a>
            <a href="#collections">Коллекции</a>
            <a href="#contact">Контакты</a>
        </div>
    </nav>
    
    <section class="hero">
        <h1>NIM</h1>
        <p>Художник, создающий уникальные образы слонов в современном искусстве</p>
        <div class="scroll-indicator">
            <svg width="30" height="30" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M7 10L12 15L17 10" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </div>
    </section>
    
    <section id="works">
        <div class="section-header">
            <h2>Избранные работы</h2>
            <p>Каждая работа — уникальное воплощение образа слона в современном искусстве</p>
        </div>
        <div class="gallery">
            <div class="artwork">
                <img src="https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Elefant the best">
                <div class="sold-badge">Продано</div>
                <div class="artwork-info">
                    <h3>Elefant the best</h3>
                    <p>Холст, масло, 120×80 см</p>
                </div>
            </div>
            <div class="artwork">
                <img src="https://images.unsplash.com/photo-1543946207-39bd91e70ca7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Veronikas Bday">
                <div class="sold-badge">Продано</div>
                <div class="artwork-info">
                    <h3>Veronikas Bday</h3>
                    <p>Акрил, дерево, 90×60 см</p>
                </div>
            </div>
            <div class="artwork">
                <img src="https://images.unsplash.com/photo-1505142468610-359e7d316be0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Elefany classic HM">
                <div class="sold-badge">Продано</div>
                <div class="artwork-info">
                    <h3>Elefany classic HM</h3>
                    <p>Смешанная техника, 80×80 см</p>
                </div>
            </div>
            <div class="artwork">
                <img src="https://images.unsplash.com/photo-1508804185872-d7badad00f7d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Elefant in home">
                <div class="price-tag">47 000 ₽</div>
                <div class="artwork-info">
                    <h3>Elefant in home</h3>
                    <p>Масло, холст, 100×50 см</p>
                </div>
            </div>
            <div class="artwork">
                <img src="https://images.unsplash.com/photo-1505142468610-359e7d316be0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Elefant in US">
                <div class="price-tag">38 000 ₽</div>
                <div class="artwork-info">
                    <h3>Elefant in US</h3>
                    <p>Акварель, бумага, 50×100 см</p>
                </div>
            </div>
            <div class="artwork">
                <img src="https://images.unsplash.com/photo-1543946207-39bd91e70ca7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Elefant">
                <div class="price-tag">137 000 ₽</div>
                <div class="artwork-info">
                    <h3>Elefant</h3>
                    <p>Гуашь, картон, 70×50 см</p>
                </div>
            </div>
        </div>
    </section>
    
    <section id="history" style="background-color: white;">
        <div class="section-header">
            <h2>Творческий путь</h2>
            <p>Эволюция стиля и художественного видения</p>
        </div>
        <div class="timeline">
            <div class="timeline-item">
                <div class="timeline-year">2015-2017</div>
                <div class="timeline-content">
                    <h3>Первые эксперименты</h3>
                    <p>Изучение различных техник и материалов. Первые работы с образами животных, поиск уникального стиля.</p>
                </div>
            </div>
            <div class="timeline-item">
                <div class="timeline-year">2018</div>
                <div class="timeline-content">
                    <h3>Формирование стиля</h3>
                    <p>Создание первой серии работ с изображением слонов. Участие в групповых выставках молодых художников.</p>
                </div>
            </div>
            <div class="timeline-item">
                <div class="timeline-year">2019-2020</div>
                <div class="timeline-content">
                    <h3>Признание</h3>
                    <p>Первые продажи работ за рубеж. Развитие темы слонов как основного художественного направления. Создание самых известных работ.</p>
                </div>
            </div>
            <div class="timeline-item">
                <div class="timeline-year">2021-н.в.</div>
                <div class="timeline-content">
                    <h3>Зрелый период</h3>
                    <p>Работы находятся в частных коллекциях в России, США и Европе. Эксперименты с новыми материалами и техниками в рамках основной темы.</p>
                </div>
            </div>
        </div>
    </section>
    
    <section id="collections">
        <div class="section-header">
            <h2>Коллекции</h2>
            <p>Тематические серии работ, объединённые общей концепцией</p>
        </div>
        <div class="collections">
            <div class="collection">
                <img src="https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="The best">
                <div class="collection-info">
                    <h3>The best</h3>
                    <p>Лучшие работы художника, получившие признание критиков и коллекционеров.</p>
                </div>
            </div>
            <div class="collection">
                <img src="https://images.unsplash.com/photo-1543946207-39bd91e70ca7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="In the world">
                <div class="collection-info">
                    <h3>In the world</h3>
                    <p>Работы, находящиеся в частных коллекциях по всему миру.</p>
                </div>
            </div>
            <div class="collection">
                <img src="https://images.unsplash.com/photo-1505142468610-359e7d316be0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Classic model">
                <div class="collection-info">
                    <h3>Classic model</h3>
                    <p>Классические работы, выполненные в традиционных техниках.</p>
                </div>
            </div>
        </div>
    </section>
    
    <section id="contact" style="background-color: white;">
        <div class="section-header">
            <h2>Контакты</h2>
            <p>Для сотрудничества и приобретения работ</p>
        </div>
        <div class="contact">
            <p>Если вас заинтересовали мои работы или вы хотите обсудить возможные проекты, пожалуйста, свяжитесь со мной.</p>
            <a href="mailto:hello@nim-artist.ru" class="contact-btn">Написать</a>
        </div>
    </section>
    
    <footer>
        <p>© 2023 NIM. Все права защищены.</p>
    </footer>
</body>
</html>
